language: node_js
node_js:
  - '5'

install:
  - npm install -g gitbook-cli
  - gitbook install
  - gitbook -V

script:
  - gitbook build src/

deploy:
  skip_cleanup: true
  provider: surge
  project: ./src/_book/
  domain: aetherya.stream
  on: master
